"""add revisoes audit_logs cache_analises tables

Revision ID: 1948b5233ff1
Revises: ef814c223749
Create Date: 2026-02-15 17:15:44.166086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1948b5233ff1'
down_revision: Union[str, Sequence[str], None] = 'ef814c223749'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cache_analises',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hash_documentos', sa.String(length=64), nullable=False),
    sa.Column('resultado', sa.JSON(), nullable=False),
    sa.Column('total_tokens_entrada', sa.Integer(), nullable=True),
    sa.Column('total_tokens_saida', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash_documentos')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=True),
    sa.Column('usuario_email', sa.String(length=200), nullable=True),
    sa.Column('acao', sa.String(length=50), nullable=False),
    sa.Column('recurso', sa.String(length=50), nullable=False),
    sa.Column('recurso_id', sa.String(length=50), nullable=True),
    sa.Column('detalhes', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('revisoes_parecer',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('parecer_id', sa.Uuid(), nullable=False),
    sa.Column('numero_revisao', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.String(length=500), nullable=True),
    sa.Column('criado_por', sa.Uuid(), nullable=True),
    sa.Column('parecer_geral', sa.String(length=30), nullable=True),
    sa.Column('comentario_geral', sa.Text(), nullable=True),
    sa.Column('conclusao', sa.Text(), nullable=True),
    sa.Column('total_itens', sa.Integer(), nullable=False),
    sa.Column('total_aprovados', sa.Integer(), nullable=False),
    sa.Column('total_aprovados_comentarios', sa.Integer(), nullable=False),
    sa.Column('total_rejeitados', sa.Integer(), nullable=False),
    sa.Column('total_info_ausente', sa.Integer(), nullable=False),
    sa.Column('total_itens_adicionais', sa.Integer(), nullable=False),
    sa.Column('itens_snapshot', sa.JSON(), nullable=True),
    sa.Column('recomendacoes_snapshot', sa.JSON(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['criado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['parecer_id'], ['pareceres.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('revisoes_parecer')
    op.drop_table('audit_logs')
    op.drop_table('cache_analises')
    # ### end Alembic commands ###
