"""create_initial_tables

Revision ID: ef814c223749
Revises: 
Create Date: 2026-02-15 00:10:11.793947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef814c223749'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('senha_hash', sa.String(length=500), nullable=False),
    sa.Column('papel', sa.String(length=20), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('pareceres',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('numero_parecer', sa.String(length=50), nullable=False),
    sa.Column('projeto', sa.String(length=200), nullable=False),
    sa.Column('fornecedor', sa.String(length=200), nullable=False),
    sa.Column('revisao', sa.String(length=10), nullable=False),
    sa.Column('status_processamento', sa.String(length=20), nullable=False),
    sa.Column('parecer_geral', sa.String(length=30), nullable=True),
    sa.Column('comentario_geral', sa.Text(), nullable=True),
    sa.Column('conclusao', sa.Text(), nullable=True),
    sa.Column('total_itens', sa.Integer(), nullable=False),
    sa.Column('total_aprovados', sa.Integer(), nullable=False),
    sa.Column('total_aprovados_comentarios', sa.Integer(), nullable=False),
    sa.Column('total_rejeitados', sa.Integer(), nullable=False),
    sa.Column('total_info_ausente', sa.Integer(), nullable=False),
    sa.Column('total_itens_adicionais', sa.Integer(), nullable=False),
    sa.Column('criado_por', sa.Uuid(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['criado_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_parecer')
    )
    op.create_table('documentos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('parecer_id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('nome_arquivo', sa.String(length=500), nullable=False),
    sa.Column('tipo_arquivo', sa.String(length=10), nullable=False),
    sa.Column('tamanho_bytes', sa.BigInteger(), nullable=True),
    sa.Column('caminho_storage', sa.String(length=500), nullable=False),
    sa.Column('texto_extraido', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parecer_id'], ['pareceres.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itens_parecer',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('parecer_id', sa.Uuid(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('descricao_requisito', sa.Text(), nullable=False),
    sa.Column('referencia_engenharia', sa.String(length=500), nullable=True),
    sa.Column('referencia_fornecedor', sa.String(length=500), nullable=True),
    sa.Column('valor_requerido', sa.Text(), nullable=True),
    sa.Column('valor_fornecedor', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=1), nullable=False),
    sa.Column('justificativa_tecnica', sa.Text(), nullable=False),
    sa.Column('acao_requerida', sa.Text(), nullable=True),
    sa.Column('prioridade', sa.String(length=10), nullable=True),
    sa.Column('norma_referencia', sa.String(length=200), nullable=True),
    sa.Column('editado_manualmente', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.CheckConstraint("prioridade IN ('ALTA','MEDIA','BAIXA')", name='ck_prioridade'),
    sa.CheckConstraint("status IN ('A','B','C','D','E')", name='ck_status'),
    sa.ForeignKeyConstraint(['parecer_id'], ['pareceres.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recomendacoes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('parecer_id', sa.Uuid(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parecer_id'], ['pareceres.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recomendacoes')
    op.drop_table('itens_parecer')
    op.drop_table('documentos')
    op.drop_table('pareceres')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
